package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Test ABO BVG site")
    void generatedTest() {
        step("https://abo.bvg.de/de/subscriber/order", () -> {
            step("// todo: just add selenium action");
        });

        step("choose any ticket", () -> {
            step("// todo: just add selenium action");
        });

        step("fill form", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://abo.bvg.de/de/subscriber/order'", () ->
            open("https://abo.bvg.de/de/subscriber/order"));

        step("Page title should have text 'Abo bestellen | BVG'", () -> {
            String expectedTitle = "Abo bestellen | BVG";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://abo.bvg.de/de/subscriber/order'", () ->
            open("https://abo.bvg.de/de/subscriber/order"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}